In [65]:
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=localhost;"
    "Database=SalesAnalytics;"
    "Trusted_Connection=yes;"
)

print("Connected Successfully!")

Connected Successfully!

In [66]:
orders = pd.read_sql("SELECT * FROM Orders", conn)

order_details = pd.read_sql("SELECT * FROM OrderDetails", conn)

products = pd.read_sql("SELECT * FROM Products", conn)

customers = pd.read_sql("SELECT * FROM Customers", conn)

returns = pd.read_sql("SELECT * FROM Returns", conn)

C:\Users\tejus\AppData\Local\Temp\ipykernel_28156\969149843.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql("SELECT * FROM Orders", conn)
C:\Users\tejus\AppData\Local\Temp\ipykernel_28156\969149843.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_details = pd.read_sql("SELECT * FROM OrderDetails", conn)
C:\Users\tejus\AppData\Local\Temp\ipykernel_28156\969149843.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql("SELECT * FROM Products", conn)
C:\Users\tejus\AppData\Local\Temp\ipykernel_28156\969149843.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql("SELECT * FROM Customers", conn)
C:\Users\tejus\AppData\Local\Temp\ipykernel_28156\969149843.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  returns = pd.read_sql("SELECT * FROM Returns", conn)

In [67]:
print("Orders:", orders.shape)
print("OrderDetails:", order_details.shape)
print("Products:", products.shape)
print("Customers:", customers.shape)
print("Returns:", returns.shape)

Orders: (80, 5)
OrderDetails: (160, 5)
Products: (10, 6)
Customers: (15, 7)
Returns: (15, 5)

In [68]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      80 non-null     int64
 1   CustomerID   80 non-null     int64
 2   EmployeeID   80 non-null     int64
 3   OrderDate    80 non-null     object
 4   OrderStatus  80 non-null     object
dtypes: int64(3), object(2)
memory usage: 3.3+ KB

In [69]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       15 non-null     int64
 1   CustomerName     15 non-null     object
 2   Gender           15 non-null     object
 3   City             15 non-null     object
 4   State            15 non-null     object
 5   CustomerSegment  15 non-null     object
 6   JoinDate         15 non-null     object
dtypes: int64(1), object(6)
memory usage: 972.0+ bytes

In [70]:
print("\nOrderDetails")
print(order_details.isna().sum())

print("\nProducts")
print(products.isna().sum())

print("\nCustomers")
print(customers.isna().sum())

print("\nReturns")
print(returns.isna().sum())

OrderDetails
OrderDetailID      0
OrderID            0
ProductID          0
Quantity           0
DiscountPercent    0
dtype: int64

Products
ProductID      0
ProductName    0
Category       0
SubCategory    0
UnitCost       0
UnitPrice      0
dtype: int64

Customers
CustomerID         0
CustomerName       0
Gender             0
City               0
State              0
CustomerSegment    0
JoinDate           0
dtype: int64

Returns
ReturnID          0
OrderDetailID     0
ReturnDate        0
ReturnQuantity    0
ReturnReason      0
dtype: int64

In [71]:
print("Orders duplicates:", orders.duplicated().sum())
print("OrderDetails duplicates:", order_details.duplicated().sum())
print("Products duplicates:", products.duplicated().sum())
print("Customers duplicates:", customers.duplicated().sum())
print("Returns duplicates:", returns.duplicated().sum())

Orders duplicates: 0
OrderDetails duplicates: 0
Products duplicates: 0
Customers duplicates: 0
Returns duplicates: 0

In [72]:
orders.dtypes

OrderID         int64
CustomerID      int64
EmployeeID      int64
OrderDate      object
OrderStatus    object
dtype: object

In [73]:
order_details.dtypes

OrderDetailID        int64
OrderID              int64
ProductID            int64
Quantity             int64
DiscountPercent    float64
dtype: object

In [74]:
products.dtypes

ProductID        int64
ProductName     object
Category        object
SubCategory     object
UnitCost       float64
UnitPrice      float64
dtype: object

In [75]:
customers.dtypes

CustomerID          int64
CustomerName       object
Gender             object
City               object
State              object
CustomerSegment    object
JoinDate           object
dtype: object

In [76]:
returns.dtypes

ReturnID           int64
OrderDetailID      int64
ReturnDate        object
ReturnQuantity     int64
ReturnReason      object
dtype: object

In [77]:
orders["OrderDate"] = pd.to_datetime(orders["OrderDate"])

customers["JoinDate"] = pd.to_datetime(customers["JoinDate"])

returns["ReturnDate"] = pd.to_datetime(returns["ReturnDate"])

In [78]:
orders.dtypes

OrderID                 int64
CustomerID              int64
EmployeeID              int64
OrderDate      datetime64[ns]
OrderStatus            object
dtype: object

In [79]:
customers.dtypes

CustomerID                  int64
CustomerName               object
Gender                     object
City                       object
State                      object
CustomerSegment            object
JoinDate           datetime64[ns]
dtype: object

In [80]:
returns.dtypes

ReturnID                   int64
OrderDetailID              int64
ReturnDate        datetime64[ns]
ReturnQuantity             int64
ReturnReason              object
dtype: object

In [81]:
orders[~orders['CustomerID'].isin(customers['CustomerID'])]

Empty DataFrame
Columns: [OrderID, CustomerID, EmployeeID, OrderDate, OrderStatus]
Index: []

In [82]:
order_details[~order_details['OrderID'].isin(orders['OrderID'])]

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, DiscountPercent]
Index: []

In [83]:
order_details[~order_details['ProductID'].isin(products['ProductID'])]

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, DiscountPercent]
Index: []

In [84]:
returns[~returns['OrderDetailID'].isin(order_details['OrderDetailID'])]

Empty DataFrame
Columns: [ReturnID, OrderDetailID, ReturnDate, ReturnQuantity, ReturnReason]
Index: []

In [85]:
Sales= orders.merge(order_details, on="OrderID", how = "inner")

In [86]:
Sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,OrderStatus,OrderDetailID,ProductID,Quantity,DiscountPercent
0,1001,101,301,2025-01-05,Completed,5001,201,1,5.0
1,1001,101,301,2025-01-05,Completed,5002,205,2,10.0
2,1002,102,303,2025-01-08,Completed,5003,203,1,5.0
3,1002,102,303,2025-01-08,Completed,5004,208,2,0.0
4,1003,103,302,2025-01-12,Completed,5005,202,1,8.0

In [87]:
Sales = Sales.merge(products, on="ProductID", how= "left")

In [88]:
Sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,OrderStatus,OrderDetailID,ProductID,Quantity,DiscountPercent,ProductName,Category,SubCategory,UnitCost,UnitPrice
0,1001,101,301,2025-01-05,Completed,5001,201,1,5.0,Laptop Pro 14,Electronics,Laptops,52000.0,72000.0
1,1001,101,301,2025-01-05,Completed,5002,205,2,10.0,Wireless Headphones,Accessories,Audio,3500.0,5999.0
2,1002,102,303,2025-01-08,Completed,5003,203,1,5.0,Smartphone X,Electronics,Mobile Phones,28000.0,42000.0
3,1002,102,303,2025-01-08,Completed,5004,208,2,0.0,Wireless Mouse,Accessories,Mouse,700.0,1299.0
4,1003,103,302,2025-01-12,Completed,5005,202,1,8.0,Laptop Air 13,Electronics,Laptops,41000.0,59000.0

In [89]:
Sales["GrossSales"]= Sales["UnitPrice"]*Sales["Quantity"]
Sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,OrderStatus,OrderDetailID,ProductID,Quantity,DiscountPercent,ProductName,Category,SubCategory,UnitCost,UnitPrice,GrossSales
0,1001,101,301,2025-01-05,Completed,5001,201,1,5.0,Laptop Pro 14,Electronics,Laptops,52000.0,72000.0,72000.0
1,1001,101,301,2025-01-05,Completed,5002,205,2,10.0,Wireless Headphones,Accessories,Audio,3500.0,5999.0,11998.0
2,1002,102,303,2025-01-08,Completed,5003,203,1,5.0,Smartphone X,Electronics,Mobile Phones,28000.0,42000.0,42000.0
3,1002,102,303,2025-01-08,Completed,5004,208,2,0.0,Wireless Mouse,Accessories,Mouse,700.0,1299.0,2598.0
4,1003,103,302,2025-01-12,Completed,5005,202,1,8.0,Laptop Air 13,Electronics,Laptops,41000.0,59000.0,59000.0

In [90]:
Sales["DiscountAmount"]= Sales["GrossSales"]*Sales["DiscountPercent"]/100
Sales[["ProductName","GrossSales","DiscountPercent","DiscountAmount"]].head()

           ProductName  GrossSales  DiscountPercent  DiscountAmount
0        Laptop Pro 14     72000.0              5.0          3600.0
1  Wireless Headphones     11998.0             10.0          1199.8
2         Smartphone X     42000.0              5.0          2100.0
3       Wireless Mouse      2598.0              0.0             0.0
4        Laptop Air 13     59000.0              8.0          4720.0

In [91]:
Sales["NetRevenue"]=Sales["GrossSales"]-Sales["DiscountAmount"]
Sales[["ProductName","GrossSales","DiscountAmount","NetRevenue"]].head()

           ProductName  GrossSales  DiscountAmount  NetRevenue
0        Laptop Pro 14     72000.0          3600.0     68400.0
1  Wireless Headphones     11998.0          1199.8     10798.2
2         Smartphone X     42000.0          2100.0     39900.0
3       Wireless Mouse      2598.0             0.0      2598.0
4        Laptop Air 13     59000.0          4720.0     54280.0

In [92]:
Sales["Cost"]=Sales["UnitCost"]*Sales["Quantity"]
Sales[["ProductName","Quantity","UnitCost","Cost"]].head()

           ProductName  Quantity  UnitCost     Cost
0        Laptop Pro 14         1   52000.0  52000.0
1  Wireless Headphones         2    3500.0   7000.0
2         Smartphone X         1   28000.0  28000.0
3       Wireless Mouse         2     700.0   1400.0
4        Laptop Air 13         1   41000.0  41000.0

In [93]:
Sales["GrossProfit"]= Sales["NetRevenue"]-Sales["Cost"]
Sales[["ProductName","NetRevenue","Cost","GrossProfit"]].head()

           ProductName  NetRevenue     Cost  GrossProfit
0        Laptop Pro 14     68400.0  52000.0      16400.0
1  Wireless Headphones     10798.2   7000.0       3798.2
2         Smartphone X     39900.0  28000.0      11900.0
3       Wireless Mouse      2598.0   1400.0       1198.0
4        Laptop Air 13     54280.0  41000.0      13280.0

In [103]:
Sales["ProfitMargin"]=Sales["GrossProfit"]/Sales["NetRevenue"]*100
Sales[["ProductName","NetRevenue","GrossProfit","ProfitMargin"]].head()

           ProductName  NetRevenue  GrossProfit  ProfitMargin
0        Laptop Pro 14    68400.00     16400.00     23.976608
1  Wireless Headphones    10798.20      3798.20     35.174381
2         Smartphone X    39900.00     11900.00     29.824561
3        Laptop Air 13    54280.00     13280.00     24.465733
4  Mechanical Keyboard     4274.05      1474.05     34.488366

In [106]:
Sales

,OrderID,CustomerID,EmployeeID,OrderDate,OrderStatus,OrderDetailID,ProductID,Quantity,DiscountPercent,ProductName,...,NetRevenue,Cost,GrossProfit,ProfitMargin,CustomerName,Gender,City,State,CustomerSegment,JoinDate
0,1001,101,301,2025-01-05,Completed,5001,201,1,5.0,Laptop Pro 14,...,68400.00,52000.0,16400.00,23.976608,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
1,1001,101,301,2025-01-05,Completed,5002,205,2,10.0,Wireless Headphones,...,10798.20,7000.0,3798.20,35.174381,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
2,1002,102,303,2025-01-08,Completed,5003,203,1,5.0,Smartphone X,...,39900.00,28000.0,11900.00,29.824561,Priya Nair,Female,Chennai,Tamil Nadu,Standard,2023-04-21
3,1003,103,302,2025-01-12,Completed,5005,202,1,8.0,Laptop Air 13,...,54280.00,41000.0,13280.00,24.465733,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
4,1003,103,302,2025-01-12,Completed,5006,207,1,5.0,Mechanical Keyboard,...,4274.05,2800.0,1474.05,34.488366,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,1078,101,301,2026-08-26,Completed,5156,206,1,5.0,Bluetooth Speaker,...,3799.05,2200.0,1599.05,42.090786,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
141,1079,103,302,2026-09-03,Completed,5157,202,1,5.0,Laptop Air 13,...,56050.00,41000.0,15050.00,26.851026,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
142,1079,103,302,2026-09-03,Completed,5158,205,2,5.0,Wireless Headphones,...,11398.10,7000.0,4398.10,38.586256,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
143,1080,110,305,2026-09-11,Completed,5159,203,1,5.0,Smartphone X,...,39900.00,28000.0,11900.00,29.824561,Meera Joshi,Female,Pune,Maharashtra,Premium,2024-05-20
144,1080,110,305,2026-09-11,Completed,5160,208,2,0.0,Wireless Mouse,...,2598.00,1400.0,1198.00,46.112394,Meera Joshi,Female,Pune,Maharashtra,Premium,2024-05-20

In [107]:
Sales= Sales[Sales["OrderStatus"]=="Completed"].copy()

In [108]:
Sales.shape

(145, 26)

In [109]:
Sales = Sales[~Sales["OrderDetailID"].isin(returns["OrderDetailID"])]

In [110]:
Sales.shape

(145, 26)

In [111]:
Sales = Sales.merge(customers, on="CustomerID", how= "left")

In [112]:
Sales

,OrderID,CustomerID,EmployeeID,OrderDate,OrderStatus,OrderDetailID,ProductID,Quantity,DiscountPercent,ProductName,...,City_x,State_x,CustomerSegment_x,JoinDate_x,CustomerName_y,Gender_y,City_y,State_y,CustomerSegment_y,JoinDate_y
0,1001,101,301,2025-01-05,Completed,5001,201,1,5.0,Laptop Pro 14,...,Bengaluru,Karnataka,Premium,2023-02-15,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
1,1001,101,301,2025-01-05,Completed,5002,205,2,10.0,Wireless Headphones,...,Bengaluru,Karnataka,Premium,2023-02-15,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
2,1002,102,303,2025-01-08,Completed,5003,203,1,5.0,Smartphone X,...,Chennai,Tamil Nadu,Standard,2023-04-21,Priya Nair,Female,Chennai,Tamil Nadu,Standard,2023-04-21
3,1003,103,302,2025-01-12,Completed,5005,202,1,8.0,Laptop Air 13,...,Mumbai,Maharashtra,Premium,2023-06-10,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
4,1003,103,302,2025-01-12,Completed,5006,207,1,5.0,Mechanical Keyboard,...,Mumbai,Maharashtra,Premium,2023-06-10,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,1078,101,301,2026-08-26,Completed,5156,206,1,5.0,Bluetooth Speaker,...,Bengaluru,Karnataka,Premium,2023-02-15,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
141,1079,103,302,2026-09-03,Completed,5157,202,1,5.0,Laptop Air 13,...,Mumbai,Maharashtra,Premium,2023-06-10,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
142,1079,103,302,2026-09-03,Completed,5158,205,2,5.0,Wireless Headphones,...,Mumbai,Maharashtra,Premium,2023-06-10,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
143,1080,110,305,2026-09-11,Completed,5159,203,1,5.0,Smartphone X,...,Pune,Maharashtra,Premium,2024-05-20,Meera Joshi,Female,Pune,Maharashtra,Premium,2024-05-20
144,1080,110,305,2026-09-11,Completed,5160,208,2,0.0,Wireless Mouse,...,Pune,Maharashtra,Premium,2024-05-20,Meera Joshi,Female,Pune,Maharashtra,Premium,2024-05-20

In [61]:
Sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 145 entries, 0 to 144
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderID            145 non-null    int64
 1   CustomerID         145 non-null    int64
 2   EmployeeID         145 non-null    int64
 3   OrderDate          145 non-null    datetime64[ns]
 4   OrderStatus        145 non-null    object
 5   OrderDetailID      145 non-null    int64
 6   ProductID          145 non-null    int64
 7   Quantity           145 non-null    int64
 8   DiscountPercent    145 non-null    float64
 9   ProductName_x      145 non-null    object
 10  Category_x         145 non-null    object
 11  SubCategory_x      145 non-null    object
 12  UnitCost_x         145 non-null    float64
 13  UnitPrice_x        145 non-null    float64
 14  GrossSales         145 non-null    float64
 15  DiscountAmount     145 non-null    float64
 16  NetRevenue         145 non-null    float64
 17  Cost               145 non-null    float64
 18  GrossProfit        145 non-null    float64
 19  ProfitMargin       145 non-null    float64
 20  CustomerName_x     145 non-null    object
 21  Gender_x           145 non-null    object
 22  City_x             145 non-null    object
 23  State_x            145 non-null    object
 24  CustomerSegment_x  145 non-null    object
 25  JoinDate_x         145 non-null    datetime64[ns]
 26  ProductName_y      145 non-null    object
 27  Category_y         145 non-null    object
 28  SubCategory_y      145 non-null    object
 29  UnitCost_y         145 non-null    float64
 30  UnitPrice_y        145 non-null    float64
 31  ProductName        145 non-null    object
 32  Category           145 non-null    object
 33  SubCategory        145 non-null    object
 34  UnitCost           145 non-null    float64
 35  UnitPrice          145 non-null    float64
 36  CustomerName_y     145 non-null    object
 37  Gender_y           145 non-null    object
 38  City_y             145 non-null    object
 39  State_y            145 non-null    object
 40  CustomerSegment_y  145 non-null    object
 41  JoinDate_y         145 non-null    datetime64[ns]
dtypes: datetime64[ns](3), float64(13), int64(6), object(20)
memory usage: 48.7+ KB

In [113]:
print(orders[['OrderDate']].dtypes)
print(customers[['JoinDate']].dtypes)

# Check total null values in sales
print("Total Null Values:", Sales.isnull().sum().sum())

OrderDate    datetime64[ns]
dtype: object
JoinDate    datetime64[ns]
dtype: object
Total Null Values: 0

In [117]:
"""Business Question 1 — Overall Sales Performance
Management wants a high-level view of business performance.
Calculate:
- Total Orders
- Total Quantity Sold
- Gross Sales
- Discount Amount
- Net Revenue
- Total Cost
- Gross Profit
- Overall Profit Margin % """
Sales.head()

,OrderID,CustomerID,EmployeeID,OrderDate,OrderStatus,OrderDetailID,ProductID,Quantity,DiscountPercent,ProductName,...,City_x,State_x,CustomerSegment_x,JoinDate_x,CustomerName_y,Gender_y,City_y,State_y,CustomerSegment_y,JoinDate_y
0,1001,101,301,2025-01-05,Completed,5001,201,1,5.0,Laptop Pro 14,...,Bengaluru,Karnataka,Premium,2023-02-15,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
1,1001,101,301,2025-01-05,Completed,5002,205,2,10.0,Wireless Headphones,...,Bengaluru,Karnataka,Premium,2023-02-15,Rahul Sharma,Male,Bengaluru,Karnataka,Premium,2023-02-15
2,1002,102,303,2025-01-08,Completed,5003,203,1,5.0,Smartphone X,...,Chennai,Tamil Nadu,Standard,2023-04-21,Priya Nair,Female,Chennai,Tamil Nadu,Standard,2023-04-21
3,1003,103,302,2025-01-12,Completed,5005,202,1,8.0,Laptop Air 13,...,Mumbai,Maharashtra,Premium,2023-06-10,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10
4,1003,103,302,2025-01-12,Completed,5006,207,1,5.0,Mechanical Keyboard,...,Mumbai,Maharashtra,Premium,2023-06-10,Amit Verma,Male,Mumbai,Maharashtra,Premium,2023-06-10

In [118]:
TotalOrders = Sales["OrderID"].nunique()

In [119]:
TotalQuantitySold= Sales["Quantity"].sum()
TotalQuantitySold

203

In [122]:
TotalGrossSales=Sales["GrossSales"].sum()
TotalGrossSales

4209670.0

In [124]:
TotalDiscountAmount = Sales["DiscountAmount"].sum()
TotalDiscountAmount

243025.43

In [126]:
NetRevenue = Sales["NetRevenue"].sum()
NetRevenue

3966644.57

In [133]:
TotalCost =(Sales["UnitCost"]*Sales["Quantity"]).sum()
TotalCost

2849700.0

In [129]:
GrossProfit = Sales["GrossProfit"].sum()
GrossProfit

1116944.57

In [134]:
OverAllProfitMargin= (GrossProfit/NetRevenue)*100
OverAllProfitMargin

28.158423329569963

In [135]:
"""Top Product Analysis
Business Question:
Management wants to identify the products generating the highest Net Revenue and Gross Profit.

For each product, calculate:
- ProductName
- Category
- TotalQuantity
- NetRevenue
- GrossProfit
- ProfitMargin"""

'Top Product Analysis\nBusiness Question:\nManagement wants to identify the products generating the highest Net Revenue and Gross Profit.\n\nFor each product, calculate:\n- ProductName\n- Category\n- TotalQuantity\n- NetRevenue\n- GrossProfit\n- ProfitMargin'

In [149]:
ProductAnalysis= Sales.groupby(["ProductName","Category"]).agg(
    TotalQuantity=("Quantity","sum"),
    NetRevenue=("NetRevenue","sum"),
    GrossProfit=("GrossProfit","sum"),
)
ProductAnalysis["ProfitMargin"]= ProductAnalysis["GrossProfit"]/ProductAnalysis["NetRevenue"]*100
ProductAnalysis.sort_values("NetRevenue",ascending=False).head(5)

,,TotalQuantity,NetRevenue,GrossProfit,ProfitMargin
ProductName,Category,,,,
Laptop Pro 14,Electronics,19,1287360.00,299360.00,23.253791
Laptop Air 13,Electronics,16,888540.00,232540.00,26.171022
Smartphone X,Electronics,21,835380.00,247380.00,29.612871
Smartphone Lite,Electronics,17,347820.00,109820.00,31.573803
Wireless Headphones,Accessories,38,215664.05,82664.05,38.330009

In [161]:
#Top 5 products by GrossProfit.
ProductAnalysis["GrossProfit"].sort_values(ascending= False).head(5)

ProductName          Category
Laptop Pro 14        Electronics    299360.00
Smartphone X         Electronics    247380.00
Laptop Air 13        Electronics    232540.00
Smartphone Lite      Electronics    109820.00
Wireless Headphones  Accessories     82664.05
Name: GrossProfit, dtype: float64

In [163]:
#High Revenue vs Low Margin(low margin as below 25%.)
ProductAnalysis[ProductAnalysis["ProfitMargin"] < 25]

,,TotalQuantity,NetRevenue,GrossProfit,ProfitMargin
ProductName,Category,,,,
Laptop Pro 14,Electronics,19,1287360.0,299360.0,23.253791

In [164]:
#Which product categories are contributing the most Revenue, Gross Profit, and Quantity Sold?

In [165]:
CategoryAnalysis = Sales.groupby("Category").agg(
    TotalQuantity=("Quantity", "sum"),
    NetRevenue=("NetRevenue", "sum"),
    GrossProfit=("GrossProfit", "sum")
)

In [166]:
CategoryAnalysis

             TotalQuantity  NetRevenue  GrossProfit
Category
Accessories            120   432183.80    172483.80
Electronics             83  3534460.77    944460.77

C:\Users\tejus\anaconda3\python.exe